/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI_CSDLPT;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.TableColumn;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author baobo
 */

public class MainFrame extends javax.swing.JFrame {
    String [] curriculumItems = new String[5];
    int id;
    String UserName;
    static Connection connServer = Main.connect;
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        TableColumn col = tbCurriculum.getColumnModel().getColumn(0);
        col.setPreferredWidth(1);
        showCurriculum();
    }

        static void  selectedServer(String server) throws SQLException {
        String dbURL;
        switch (server) {
            case "Server 1":
                dbURL = "jdbc:sqlserver://localhost:45678;databaseName=KanBos;user=sa;password=as" ;
                Connection conn1 = connect(dbURL);
                connServer = conn1;
                break;
            case "Server 2":
                dbURL = "jdbc:sqlserver://localhost:45679;databaseName=KanBos;user=sa;password=as" ;
                Connection conn2 = connect(dbURL);
                connServer = conn2;
                break;
            case "Server 3":
                dbURL = "jdbc:sqlserver://localhost:45670;databaseName=KanBos;user=sa;password=as" ;
                Connection conn3 = connect(dbURL);
                connServer = conn3;
                break;
            case "Server4":
                Connection conn4 = connect("45671");
                connServer = conn4;
                break;
                
            default:
                break;
        }
    }
        public static Connection connect(String dbURL) throws SQLException {
//		String dbURL = "jdbc:sqlserver://localhost:+" + port + ";databaseName=DANGKYTOUR;user=sa;password=root";
        Connection conn = null;
        conn = DriverManager.getConnection(dbURL);

        //DatabaseMetaData dm = (DatabaseMetaData) conn.getMetaData();
        //System.out.println("Product name: " + dm.getURL());

        return conn;
    }
    
    public ArrayList<Curriculum>curriculumList(){
        ArrayList<Curriculum> curriculumList = new ArrayList<>();
        
        //String url = "jdbc:sqlserver://localhost:45678;databaseName=KanBos;user=sa;password=bk";
        try {
            Connection conn = connServer;
            String query = "SELECT Curriculum.ID, Curriculum.curriculum, Curriculum.author, School.school, Curriculum.speciality  FROM Curriculum "
                    + "INNER JOIN School ON Curriculum.ID_School = School.ID";
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery(query);
            Curriculum curriculum;
            while (rs.next()) {                
                curriculum = new Curriculum(rs.getInt("ID"),rs.getString("curriculum"), rs.getString("author"), rs.getString("school"), rs.getString("speciality"));
                curriculumList.add(curriculum);
            }
        } catch (SQLException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        return curriculumList;
    }
    
    void showCurriculum(){
        ArrayList<Curriculum> list = curriculumList();
        DefaultTableModel model = (DefaultTableModel) tbCurriculum.getModel();
        Object[] row = new Object[6];
        for (int i = 0; i < list.size(); i++) {
            row[0] = list.get(i).getId();
            row[1] = list.get(i).getName();
            row[2] = list.get(i).getAuthor();
            row[3] = list.get(i).getSchool();
            row[4] = list.get(i).getSpeciality();
             model.addRow(row);
        }
    }
    
    public String[] getRowAt(int row) {
     String[] result = new String[5];

     for (int i =0; i <5; i++) {
         if (i == 0) {
             id = (int) tbCurriculum.getModel().getValueAt(row, i);
              result[0] = String.valueOf(id);
         }
         else{
             result[i] = (String) tbCurriculum.getModel().getValueAt(row, i);
         }
        
         //System.out.println("eee"+result[i]);
     }

     return result;
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tfUserName = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        serverList = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbCurriculum = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Hệ thống quản lý");

        jInternalFrame1.setVisible(true);

        jLabel1.setFont(new java.awt.Font("Serif", 1, 32)); // NOI18N
        jLabel1.setText("HỆ THỐNG QUẢN LÝ GIÁO TRÌNH TRONG ĐÀ NẴNG");

        jLabel3.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        jLabel3.setText("Xin Chào");

        tfUserName.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        tfUserName.setText("Xin chào");

        btnAdd.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        btnAdd.setText("Thêm");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnEdit.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        btnEdit.setText("Sửa");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnDelete.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        btnDelete.setText("Xoá");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        serverList.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        serverList.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Server 1", "Server 2", "Server 3" }));
        serverList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serverListActionPerformed(evt);
            }
        });

        tbCurriculum.setFont(new java.awt.Font("Serif", 0, 11)); // NOI18N
        tbCurriculum.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Tên Giáo Trình", "Tác Giả", "Trường Đại Học", "Ngành"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbCurriculum.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbCurriculumMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbCurriculum);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGap(0, 29, Short.MAX_VALUE)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 805, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jInternalFrame1Layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tfUserName)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(serverList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel1)))
                .addGap(0, 29, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(103, 103, 103)
                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(101, 101, 101))
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(43, 43, 43)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(serverList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDelete)
                    .addComponent(btnEdit)
                    .addComponent(btnAdd))
                .addContainerGap(64, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void serverListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serverListActionPerformed
        String selectedServer = serverList.getSelectedItem().toString();
        try {
            selectedServer(selectedServer);
            System.out.println("done");
        } catch (SQLException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_serverListActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        EditFrame editFrame = new EditFrame();
        System.out.println(curriculumItems[0]);
        editFrame.getCurriculum(curriculumItems[0],curriculumItems[1],curriculumItems[2],curriculumItems[3],curriculumItems[4]);
        dispose();
        editFrame.setVisible(true);
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        dispose();
        AddFrame addFrame = new AddFrame();
        addFrame.setVisible(true);
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        int respone = JOptionPane.showConfirmDialog(null, "Bạn có chắc xoá tài liệu này ko", "Xác nhận", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (respone == JOptionPane.YES_OPTION) {
            String url = "jdbc:sqlserver://localhost:45678;databaseName=KanBos;user=sa;password=as";
        try {
            Connection conn = connServer;
            String query = "DELETE FROM Curriculum WHERE ID = ?";
            PreparedStatement pst = conn.prepareStatement(query);
            pst.setInt(1, id);
            
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Sửa tài liệu thành công");
            dispose();
            MainFrame mainFrame = new MainFrame();
            mainFrame.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(AddFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        } 
        else if(respone == JOptionPane.NO_OPTION)  {
            System.out.println("NO");
        }
        else if(respone == JOptionPane.CLOSED_OPTION){
            System.out.println("CLOSE");
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void tbCurriculumMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbCurriculumMouseClicked
        DefaultTableModel model = (DefaultTableModel) tbCurriculum.getModel();
        int selectedCurriculum = tbCurriculum.getSelectedRow();
        
        curriculumItems = getRowAt(selectedCurriculum);
    }//GEN-LAST:event_tbCurriculumMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
              
            }
        });
    }

public void helloUserName(String name){
    UserName = name;
    tfUserName.setText(name);
}
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> serverList;
    private javax.swing.JTable tbCurriculum;
    private javax.swing.JLabel tfUserName;
    // End of variables declaration//GEN-END:variables
}
